### ISSUE TITLE
Feature pull request

### ISSUE THREAD

**Issue by avifatal** [aryehraber/statamic-fetch#41]
Hi,
When fetching deep items, sometimes you can really deep and bring a huge amount of data.
For example, if you bring a collection with relation to `Page`, in most cases you just need the title.
So, how about this:

`/!/Fetch/collection/navigation?`**onlyDeepItems[page]=url,title**

So when the `relatedData` method fetching `page`, it will only bring url and title, and not the entire object.

I have it working in a gist: https://gist.github.com/avifatal/380e571149618b5a1c15030a7a14a29c
Just follow the `$this->onlyDeepItems` member...
I think my naming is a little bit odd, but nevertheless, will you consider merging such feature?
Thanks

**Comment by aryehraber** [comment]
Hi @avifatal, thanks for opening an issue to offer a PR 😊 

While I agree that this idea would be hugely useful, I'm not accepting any new PRs at this time due to Fetch not having any Test coverage, to ensure no breaking changes slip in. Also, having had a quick look at your gist, I think I'd prefer tackle the problem in a different way (had some ideas in the past but didn't have time to explore fully).

Thanks again, and feel free to fork this repo to maintain your own version of Fetch with these changes.
