### ISSUE TITLE
500 when fetching in production

### ISSUE THREAD

**Issue by andyra** [aryehraber/statamic-fetch#49]
I uploaded my Statamic site to production and I'm noticing that fetch requests are returning 500.

- Using Fetch 4.4.0 on Statamic 2.11.9
- Locally, I can visit `http://localhost:1234/!/Fetch/collection/albums` and get page full of wonderful JSON data
- In Production, if I visit `http://thiseveningsshow.com/!/Fetch/collection/albums`, I get a "Whoops, something went wrong" error and a 500 status code.
- Production settings in **/settings/addons/fetch.yml** look like this (same as local):

  ```
  deep: false
  nested: false
  enable_api_key: false
  ```

This is what the log is spitting out every time I make a request:

```
[2019-02-13 01:51:05] production.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'syntax error, unexpected 'global' (T_GLOBAL), expecting identifier (T_STRING)' in /public_html/tes/site/addons/Fetch/Fetch.php:162
Stack trace:
#0 {main}
```

**Comment by aryehraber** [comment]
Just off the top of my head looking at the error, I think the PHP version on your prod server is out of date. What version are you using?

**Comment by andyra** [comment]
@aryehraber Looks like the server is running PHP 5.6.

**Comment by aryehraber** [comment]
Bingo, Fetch requires PHP 7+, the error should go away after upgrading. But tbh, you'll probably want to upgrade anyway since PHP 5.6 (and 7.0) have reached end of life and are no longer being supported (http://php.net/supported-versions.php).

Closing this issue for now, but feel free to reopen if this error continues after upgrading.
