### ISSUE TITLE
Query a collection index

### ISSUE THREAD

**Issue by joshhornby** [aryehraber/statamic-fetch#54]
According to the docs you can pass an `index` to a collection in order to query a collection.

Can you provide a working example of this as I can't get it to work, I've run `php please search:update collections/resources` on my resources collection. My searchable field is called `category` but when I try `collection/resources?index=category&query=foo` the whole collection is returned and no searching has taken place.

According to the docs this should work.

Any help is greatly appreciated. 

Thanks

**Comment by aryehraber** [comment]
Looks like you're not quite using this feature correctly. It's been a while since I used this myself but let me try and explain:

You can't specify the searchable field via the query -- instead you need to setup your Collection Index as per Statamic's docs: https://docs.statamic.com/search#collection-indexes.

Once that is setup, run `php please search:update collections/resources` again to re-index the collection.

Now, you should be able to search that collection using the index and query params (found a mistake in the docs), here's an example that _should_ work:

`http://domain.com/!/Fetch/search?index=collections/resources&query=foo`

**Comment by joshhornby** [comment]
Thanks for such a quick reply. I can confirm that `http://domain.com/!/Fetch/search?index=collections/resources&query=foo` works as expected. 

Assume it's not possible to get a list of indexable fields back? so in my example it would be a list of `categories`

Once again thanks for the help.

**Comment by aryehraber** [comment]
Great, thanks for testing! Will fix up the docs when I get a moment.

Not completely sure what you mean with "a list of indexable fields"?

**Comment by joshhornby** [comment]
Sorry, I should of said a list of values from the indexable fields. So if I'm indexing `category` I want to see all the values that are indexed.

**Comment by aryehraber** [comment]
Ah right, I don't think that's possible atm. Fetch doesn't currently support Taxonomies which is presumably where these categories are (or could be) stored.
