### ISSUE TITLE
Page Fieldtype within Replicator

### ISSUE THREAD

**Issue by edolyne** [aryehraber/statamic-fetch#8]
I'm running a project where I'm using a Pages fieldtype within replicator and when I access the json data only the page id is returned, rather than page data. Is it possible to modify this so that relations within replicator display their proper related item?

**Comment by aryehraber** [comment]
Hi @edolyne! Fetch _should_ be fetching related data too (granted there is an id it can find). Are you using the `deep` option? https://github.com/aryehraber/statamic-fetch#settings

**Comment by edolyne** [comment]
Hi @aryehraber I do have the `deep` option turned on in the CP. Right now it just appears to be returning an ID which is connected to a `.md` file

**Comment by aryehraber** [comment]
Sorry, I'm not sure in that case... It's very possible something broke in the most recent version(s) of Statamic — it's been a while since I used/tested the addon myself. 

I will make a note to look into this at some point, but can't promise anything short-term I'm afraid. If you are comfortable with PHP, please feel free to dive into the code and debug the issue, I'm happy to accept PRs!

**Comment by edolyne** [comment]
@aryehraber No worries, my PHP skills aren't ninja level, but I was able to work through the issues I was seeing with Replicator and have them working correctly. I opened a PR reflecting the changes I made to get it working. Feel free to suggest edits if need be.

**Comment by aryehraber** [comment]
Awesome thanks! I'll review this soon.

**Comment by aryehraber** [comment]
Thanks again for reporting this issue and submitting the PR!

Latest release should address this issue! Please re-open if you are still seeing this bug occur.
